

export interface Clientes {
  _id:             string;
  imagen:          null | string;
  nombreCompleto:  string;
  identidad:       string;
  numeroTelefono:  string;
  correo:          string;
  estado:          string;
  fechaIngreso:    Date;
  idPlan:          string;
  diasRestantes:   number;
  __v:             number;
  rutinaAsignada?: string;
}

// Generated by https://quicktype.io

// export interface Clientes2 {
//   _id:            string;
//   imagen:         string;
//   nombreCompleto: string;
//   identidad:      string;
//   numeroTelefono: string;
//   correo:         string;
//   estado:         Estado;
//   idPlan:         IDPlan;
//   fechaIngreso?:  string;
//   __v:            number;
//   diasRestantes?: number;
// }

// export enum Estado {
//   Activo = "Activo",
//   Inactivo = "Inactivo",
//   Pendiente = "Pendiente",
// }

// export enum IDPlan {
//   The65Dd5E427D9B0513Dce45D5E = "65dd5e427d9b0513dce45d5e",
// }
