// Generated by https://quicktype.io

// export interface Productos {
//     _id:             string;
//     imagen:          string;
//     nombreProducto:  string;
//     descripcion:     string;
//     precio:          number;
//     cantidadEnStock: number;
//     createdAt:       string;
//     updatedAt:       string;
//     idproducto:      number;
//     __v:             number;
// }



// export interface Productos {
//   _id:             string;
//   imagen:          string;
//   nombreProducto:  string;
//   descripcion:     string;
//   precio:          number;
//   cantidadEnStock: number;
//   createdAt:       string;
//   updatedAt:       string;
//   __v:             number;
// }

export interface Productos {
  _id:             string;
  imagen:          string;
  nombreProducto:  string;
  descripcion:     string;
  precio:          number;
  cantidadEnStock: number;
  estado:          string;
  createdAt:       string;
  updatedAt:       string;
  __v:             number;
}

