// Generated by https://quicktype.io

export interface Factura {
  _id:              string;
  idcliente:        string;
  nombreCliente:    string;
  fecha:            Date;
  metodoPago:       string;
  idPlan:           string;
  precioPlan:       number;
  idproducto:       null;
  precioProducto:   null;
  CantidadProducto: null;
  subtotal:         number;
  descuento:        null;
  totalPagar:       number;
  createdAt:        Date;
  updatedAt:        Date;
  numeroFactura:    number;
  __v:              number;
}
